version: '3.9'

services:
  tst-postgres:
    image: postgres:latest
    shm_size: 256M
    restart: always
    container_name: 'tst-postgres'
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "44321:5432"